callstack: deprecate all classes that were moved to core
eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator pull request #16
Opened 2024-04-02 19:10 UTC by arfio

Deprecate all the classes from callstack and analysis that were moved to core. Change the classes that were not moved to depend on profiling.core and profiling.core.tests.
Depends on https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/51

2024-04-10 17:04 UTC, bhufmann requested changes
The Trace Compass incubator project doesn't provide any releases, since it's an incubator project. However, we update the version number whenever Trace Compass mainline is released, just to have some tracking (even if it's not a release :-)). 

So, currently it's at 0.9.0 and you will have to update all deprecated annotations to since="0.10.0".  9.4 is the Trace Compass mainline release and can't be used here. I commented only on 2 representative APIs to change. This comment is valid for all the others.

I noticed that the build is failing, because other plug-ins using deprecated APIs. This are settings that we chose for this project. You, could either change the setting or change the implementation to use the Trace Compass mainline APIs instead. I prefer the latter.

2024-04-10 17:17 UTC, arfio commented on callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/concepts/ICallStackSymbol.java
> +@Deprecated(since="9.4", forRemoval=true)
Done.

2024-04-10 17:17 UTC, arfio commented on callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/concepts/AggregatedCallSite.java
> +@Deprecated(since="9.4", forRemoval=true)
Done.

2024-04-10 17:19 UTC, arfio commented
Thank you for the review, I have changed the deprecation version argument like you suggested. For the other plug-ins using the deprecated API, I have another pull request opened for this: https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/18

2024-04-12 18:55 UTC, bhufmann requested changes
To fix the build, change the settings for using deprecated APIs in ROCm plug-in to warning:
https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/blob/ddb25ba7240ef442c0571706f1a4eb6e319cba37/analyses/org.eclipse.tracecompass.incubator.rocm.core/.settings/org.eclipse.jdt.core.prefs#L35

2024-04-16 18:31 UTC, bhufmann approved these changes
Thanks for this contribution. Looks good to me.

2024-04-16 19:33 UTC, merged