Add Java GC Logs
eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator pull request #42
Opened 2024-06-23 01:25 UTC by MatthewKhouzam

This feature is taken from the Eclipse JIFA project, the code was slightly tweaked, removing certain dependencies such as Lombok and SL4J, but it works well, is well tested and brings in several new views that are of interest:

* Java Memory VS Time, in the counters views, one can see the memory status by pool
* GC latency analysis: Shows the amount of time spent in the GC.

The code that will be kept if JIFA makes a jar for GC parsing would be GCTrace.java as it is the adapter between the GCModel and Trace Compass. Special attention in the reivew should be put there.

Known Issues:
* The GC log is entirely read to ram in the init phase. this can freeze the UI thread.
* The GC parser doesn't always read GC events as it changes from one JVM to another.

2024-07-25 15:17 UTC, arfio requested changes
Thank you for this addition that will improve java program performance analysis. Is it possible to add instructions on how to get a GC trace or give a link to those instructions ? Aside from that I put some small comments to improve maintainability.

2024-07-29 22:08 UTC, MatthewKhouzam commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/GCTrace.java
> +            aspects.add(2, simpleAspect("Allocation")); //$NON-NLS-1$
It was for the order. Basically content is big and people ignore what comes after it.

2024-07-29 22:10 UTC, MatthewKhouzam commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/GCTrace.java
> +            aspects.add(2, simpleAspect("Allocation")); //$NON-NLS-1$
I am now using i++ all the way.

2024-07-29 22:14 UTC, MatthewKhouzam commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/GCTrace.java
> +        fields.add(new TmfEventField("Allocation", event.getAllocation(), null)); //$NON-NLS-1$
Done!

2024-07-29 22:14 UTC, MatthewKhouzam commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/xmlanalysis/gc_analysis.xml
Yes, look in the tests plugin!

2024-07-29 22:15 UTC, MatthewKhouzam commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/util/Constant.java
Done!

2024-08-01 18:23 UTC, MatthewKhouzam commented
how to log in GC. I will add to wiki.

Java 8: Use -Xloggc:<file> -XX:+PrintGCDetails -XX:+PrintGCDateStamps.
Java 9+: Use -Xlog:gc*:file=<file> or more specific logging options.

2024-08-02 19:08 UTC, arfio commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/util/Constant.java
is it ?

2024-08-02 19:12 UTC, arfio commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/xmlanalysis/gc_analysis.xml
It seems that most of those traces are just samples and not a complete trace ?

2024-08-02 19:17 UTC, MatthewKhouzam commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/util/Constant.java
this one is the code from Jifa. I ddin't modify it. Want it anyway?

2024-08-05 14:28 UTC, arfio commented on tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/util/Constant.java
Yes, I think we should put the one they use for the other files.

2024-08-20 19:40 UTC, arfio approved these changes
LGTM !

2024-08-20 19:44 UTC, MatthewKhouzam commented
Thanks!

2024-08-20 19:45 UTC, merged