[server] Add trace properties to the Trace instance
eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator pull request #79
Opened 2024-09-20 14:10 UTC by siwei-zhang-work

The purpose of this commit is to get the trace properties using tsp. The "properties" attribute will be in the trace instance, and it will be filled if the opened trace implements ITmfPropertiesProviders.

Example:
{
  "name": "string",
  "path": "string",
  "nbEvents": 0,
  "start": 0,
  "indexingStatus": "RUNNING",
  "end": 0,
  "properties":
  {
	"hostname": "qemu1",
        "clock_offset": "1450192743562703624"
  },
  "UUID": "f50af7e0-0dd5-4361-ab96-2e04f7bc7e30"
}

[Added] "properties" field in the returned Trace instance 
[Changed] Trace instrance will be created when "/traces" is queried instead of when "/experiments" is queried.

2024-09-20 15:47 UTC, siwei-zhang-work commented
Creating a separate trace instance doesn't feel like a clean solution, but I haven't found a better workaround. The issue is that when the experiment instance is disposed, it also disposes of the trace instance, but the TSP requires the trace instance to persist. Do you have any alternative suggestions for handling this?

2024-09-20 19:39 UTC, MatthewKhouzam approved these changes
I like it.

2024-09-23 15:35 UTC, bhufmann requested changes
Thanks for this contribution. @siwei-zhang-work small comment.

2024-09-23 15:35 UTC, bhufmann commented on trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Trace.java
This class should also be updated because it's used with swagger to create the TSP API doc. Could you please update it?

Also, after that could you please also generate a new API and upload it as PR to the trace-server-protocol repository?
https://github.com/eclipse-cdt-cloud/trace-server-protocol?tab=readme-ov-file#generate-the-api

2024-09-26 13:41 UTC, bhufmann approved these changes
Looks good to me. Thanks for the contribution. I'll merge it after a successful build.

2024-09-26 14:33 UTC, merged

2024-09-26 14:33 UTC, bhufmann commented
I'll cherry-pick it to master.